### ISSUE TITLE
Vyper Compatibility

### ISSUE THREAD

**Issue by ControlCplusControlV** [Certora/gambit#16]
Hey, sorry if I missed it in the docs, but is it possible to run Gambit against a Vyper contract?

**Comment by chandrakananandi** [comment]
Hi there! At the moment Gambit doesn't support vyper unfortunately. We might add it in the future but that's not in the immediate plans for Gambit. I will let you know if anything changes!

**Comment by ControlCplusControlV** [comment]
No worries, already got one mutation working with a Vyper port [Jade](https://github.com/ControlCplusControlV/Jade)!
