### ISSUE TITLE
Create a log file of all generated mutants along with meta data

### ISSUE THREAD

**Issue by bkushigian** [Certora/gambit#4]
It's helpful to have an overview/summary of generated mutants, which rules generated them, which files the mutants belong to, etc etc. Here is an example from Major's `mutants.log`:

```
8:EVR:<IDENTIFIER(org.apache.commons.csv.CSVFormat)>:<DEFAULT>:org.apache.commons.csv.CSVFormat$Predefined@getFormat():230:format |==> null
9:LVR:FALSE:TRUE:org.apache.commons.csv.CSVFormat:249:false |==> true
10:LVR:TRUE:FALSE:org.apache.commons.csv.CSVFormat:249:true |==> false
```

If I were to change anything about this I'd say that this should be in a CSV format (parsing is a little tricky, and the weird ":" delimiter runs into issues w/ the ternary expression `a ? b : c` anyway, so we're not really avoiding any difficulties by avoiding commas)

**Comment by BenTheKush** [comment]
PR #14 addresses this
